name: Build Index

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate index.json
        env:
          INDEX_GH_USER: "sepiol2023"          # hardcoded (muda aqui se quiser)
          INDEX_GH_REPO: "x9a-mem-2025-xpto"   # hardcoded (muda aqui se quiser)
          INDEX_GH_BRANCH: "main"              # hardcoded
        run: |
          python --version
          python scripts/gen_index.py

      - name: Commit & push if changed
        run: |
          if git status --porcelain | grep -q "index.json"; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add index.json
            git commit -m "chore(index): update index.json [skip ci]"
            git push
          else
            echo "Nada para commitar."
          fi
